<?php
namespace zobe\TaskInfo;

interface LifeTimeTaskInfoInterface
{
    /**
     * Get start time in float, generated by microtime(true)
     *
     * @see http://php.net/manual/en/function.microtime.php
     * @return float
     */
    public function getStartTime();

    /**
     * do not use
     *
     * use it if you implements task info sender
     * @param float $startTime_LifeTimeTaskInfoTrait
     */
    public function setStartTime_LifeTimeTaskInfoTrait($startTime_LifeTimeTaskInfoTrait = null);

    /**
     * Get end time in float, generated by microtime(true)
     *
     * If the task is still active, this will return -1.0.
     *
     * @see http://php.net/manual/en/function.microtime.php
     * @return float
     */
    public function getEndTime();

    /**
     * do not use
     *
     * use it if you implements task info sender.
     * use it before promise->success() or fail().
     *
     * @param float $endTime_LifeTimeTaskInfoTrait
     */
    public function setEndTimeLife_TimeTaskInfoTrait($endTime_LifeTimeTaskInfoTrait = null);

    /**
     * Get duration milliseconds from start time.
     *
     * If the task has already completed, this will return duration from start time to end time.
     *
     * @return float time in milliseconds
     */
    public function getDurationMilliseconds():float;
}

